server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dropbaba_auth
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

jwt:
  secret: your_jwt_secret_key
  expiration: 86400000 # 1 day in ms

management:
  endpoints:
    web:
      exposure:
        include: "*"
