server:
  port: 8084

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/dropbaba_users
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  spring:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
