server:
  port: 8086

spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:mysql://localhost:3306/dropbaba_delivery
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  order:
    ready:
      queue: order.ready.queue

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  routes:
    - id: delivery-service
      uri: lb://delivery-service
      predicates:
        - Path=/api/deliveries/**
