name: Build & Test Auth Service

on:
  push:
    paths:
      - 'auth-service/**'
  pull_request:
    paths:
      - 'auth-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./auth-service/gradlew

      - name: Build Auth Service
        run: |
          cd auth-service
          ./gradlew build --no-daemon
